// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '!--------Your API KEY--------!',
    appId: '!--------Your APP ID--------!',
    messagingSenderId: '!--------Your SENDER ID--------!',
    projectId: '!--------Your PROJECT ID--------!',
    authDomain: '!--------Your AUTH DOMAIN--------!',
    storageBucket: '!--------Your STORAGE BUCKET--------!',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '!--------Your API KEY--------!',
    appId: '!--------Your APP ID--------!',
    messagingSenderId: '!--------Your SENDER ID--------!',
    projectId: '!--------Your PROJECT ID--------!',
    storageBucket: '!--------Your STORAGE BUCKET--------!',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '!--------Your API KEY--------!',
    appId: '!--------Your APP ID--------!',
    messagingSenderId: '!--------Your SENDER ID--------!',
    projectId: '!--------Your PROJECT ID--------!',
    storageBucket: '!--------Your STORAGE BUCKET--------!',
    iosClientId:
        '!--------Your IOS CLIENT ID--------!', // Only needed for iOS standalone apps
    iosBundleId:
        '!--------Your IOS BUNDLE ID--------!', // Only needed for iOS standalone apps
  );
}
